#14: SignUp Verification
titapapunne/MoreThanWords pull request #53
Opened 2020-10-26 16:10 UTC by kiranmisner

Given credentials, it should check salesforce to see if you are verified to be on the app (Contacts object). Style/Error currently there but might need changing. On my branch, I've added the <SignUp> on App.js and used the start scripts to run it.

2020-10-30 01:23 UTC, titapa-punpun requested changes
This is a really good PR - great work so far!! I made a few comments on some of the files - very minor refactoring for those. Please also add back the ```envTemplate``` file (not supposed to be deleted). Thanks!

2020-10-30 01:23 UTC, titapa-punpun commented on frontend/components/SignUp.js
> +			var verify = await fetch(`http://130.64.218.142:5000/verifySignUp?firstname=${this.state.firstname}&lastname=${this.state.lastname}&email=${this.state.email}`)
Try not to hard code. You can replace the IP address with ```${Constants.manifest.extra.apiUrl}``` so it pulls your IP from ```app.config.json```

2020-10-30 01:23 UTC, titapa-punpun commented on frontend/components/SignUp.js
> +			// consider making this a POST request, considering we are passing sensitive user data like password
Good thought! It might actually be ok as is - the URL path and query string params for all HTTP methods are encrypted, and so are POST bodies. 

https://https.cio.gov/faq/#:~:text=An%20encrypted%20HTTPS%20request%20protects,encrypted%2C%20as%20are%20POST%20bodies

2020-10-30 01:23 UTC, titapa-punpun commented on backend/app.py
> +	result = sf.query(format_soql("SELECT Id, Email FROM Contact WHERE (email = {email_value} AND name={full_name})", email_value=email, full_name=name))
nice!!!

2021-02-13 16:15 UTC, closed without merging

2021-02-13 16:16 UTC, jchin01 commented
Used the verify signup endpoint written