#20 Create Progress Bars for Pods (on Home Screen)
titapapunne/MoreThanWords pull request #73
Opened 2020-12-06 08:01 UTC by soph-yang

2020-12-09 03:44 UTC, titapa-punpun requested changes
You have some really great stuff going here! Please see individual files for comments - thanks :)

2020-12-09 03:44 UTC, titapa-punpun commented on backend/app.py
> +    return outcomes_result;
Great job with this endpoint and getting the backend connected to SF!! However, for security reasons, we'd want to assert that the email and name of query matches the email and name used to login. This is to hopefully prevent people from quering for other people's outcome results. This will need to happen after we have the login tokens all setup.

2020-12-09 03:44 UTC, titapa-punpun commented on frontend/app.config.js
> +    apiUrl: 'http://10.245.69.61:5000',
Remember to not push this! I often forget too

2020-12-09 03:44 UTC, titapa-punpun commented on frontend/components/pod_components/TraineePod.js
> +	 */
Really appreciate the good documentation!

2020-12-09 03:44 UTC, titapa-punpun commented on frontend/utils/auth 2.js
> +import jwtDecode from "jwt-decode";
I see an `auth.js` file in `staging`'s `frontend/utils` by Yichen - not sure why this file is showing up in this PR file changes? It shouldn't go into `staging` so I'd delete this file

2020-12-09 03:44 UTC, titapa-punpun commented on frontend/components/pod_components/TraineePod.js
> +              }
I'd suggest talking to Yichen about how to get this piece of data - they're stored in one of the tokens he's working on.

2020-12-09 03:44 UTC, titapa-punpun commented on frontend/components/pod_components/PodProgressBar.js
> +
Love the animation! Very cool

2020-12-09 15:44 UTC, titapa-punpun requested changes

2020-12-09 15:44 UTC, titapa-punpun commented on backend/app.py
> +@app.route("/PodProgressBar")
I'd consider naming this endpoint something like `/TraineeProgressBar` because in the near future, we'll most likely have 2 more endpoints for the 2 other pods: `/AssociateProgressBar` and `/PartnerProgressBar`. All 3 endpoints can call the same function and pass it a parameter to specify which pod's progress bar info it's querying for. The parameter would be developer specified, not user specified.

2020-12-09 15:44 UTC, titapa-punpun commented on backend/app.py
> +    outcomes_result = sf.query(format_soql("SELECT TR_CareerExpl_Outcomes__c, TR_Competency_Outcomes__c, TR_LifeEssentials_Outcomes__c FROM Trainee_POD_Map__c WHERE (Contact__r.email = {email_value}
Noah told us to just query to see if the email matches and that we don't need to worry about whether the first and last name matches

2021-02-03 15:27 UTC, jchin01 commented
There has been updates/changes in staging. Please pull from staging, merge into your branch, and resolve any merge conflicts. Then I can review your code again

2021-02-03 15:31 UTC, jchin01 commented
just from a quick glance there are some endpoints that you wrote that look similar/ almost the same as some that have already been written and merged into staging. See if you can use those endpoints so we dont have so much redundant code. If it doesn't work for you that fine, just resolve any conflicts and I will then be able to run your app and review it

2021-02-10 17:52 UTC, jchin01 commented on frontend/components/pod_components/TraineePod.js
> +const LIFE_TOTAL_OUTCOMES = 2
This works for now, but when we move away from hard coding this you will need to think about potentially writing an endpoint that could give you the total amount for each outcome.

2021-02-10 18:16 UTC, jchin01 approved these changes

2021-02-10 18:25 UTC, jchin01 approved these changes

2021-02-10 18:26 UTC, jchin01 approved these changes

2021-02-12 17:00 UTC, titapa-punpun approved these changes

2021-02-12 17:02 UTC, merged