Mtw 21
titapapunne/MoreThanWords pull request #83
Opened 2021-02-13 18:21 UTC by ryanbeckwith

# Overview

The frontend components for a generalizable Outcomes page are included in this PR, as well as backend endpoints to dynamically update Task and Outcome components based on Salesforce data. Frontend infrastructure for querying such endpoints is included as well. Furthermore, this PR includes code for updating Salesforce checkbox fields when the user checks off tasks on the frontend.

In the future, we plan to utilize the authorization token framework to obtain individualized user data so that the values of each checkbox are specific to each user. Currently, our testing only involves Trainee Pod TR-1 and Youth FakeD.

If there are any other questions about the content of this PR, feel free to ask either myself, Julia, or Alec!

# Steps to Test this PR:

1. Load the Expo app on a mobile device.
2. Manually verify that frontend interaction successfully updates Salesforce for example user data.

# Standard Checklist:

- [x] Does the code work? Does it perform its intended function, the logic is correct etc.
- [x] Have you merged the most recent version of staging into your branch?
- [x] Are all merge conflicts resolved? 
- [x] Can any logging or debugging code be removed? (Any debugging statements should be removed)
- [x] Is the `diff` the **minimum amount** needed to achieve this ticket's goal?

2021-02-13 19:44 UTC, titapa-punpun requested changes
Solid PR!! Can you delete `package.json`, `webpack.config.js`, and `yarn.lock` in the root directory? They should only be in the `frontend` folder. Other than that, please see comments in the individual files - thanks!

2021-02-13 19:44 UTC, titapa-punpun commented on frontend/components/outcomes/OutcomesScreen.js
> +    );
Can you add a valid default state that shows if it errors or if there's no data to fetch? 
Default Error Message can be: "There are no outcomes to display. Please contact your manager or More Than Words administrator if you think this is an error."

2021-02-13 19:44 UTC, titapa-punpun commented on frontend/components/outcomes/Outcome.js
> +    ];
I think the `defaultData` should be empty and if there is no data to fetch, this component should not render and the app should display an error message (see other comment).

2021-02-13 19:44 UTC, titapa-punpun commented on frontend/components/outcomes/Task.js
> +        );
If YDM approved the task, it should be greyed out, the youth checkbox should be disabled, and the star should be disabled as well. Can't see why youth would want to star a task that's already been approved.

2021-02-13 19:44 UTC, titapa-punpun commented on frontend/components/outcomes/Task.js
> +        axios.get(server_add + "/updateCheckbox", {
There should be error handling for this endpoint -- what if it fails?

2021-02-13 19:44 UTC, titapa-punpun commented on frontend/components/outcomes/Task.js
> +            updated_value = "True"
Can reuse bool:
`updated_value = !this.state.checked`

2021-02-13 19:44 UTC, titapa-punpun commented on frontend/components/outcomes/OutcomesHome.js
> +/*
Is this file a duplicate of `OutcomesScreen.js`? I couldn't find any usages of this component.

2021-02-13 19:44 UTC, titapa-punpun commented on frontend/components/outcomes/Task.js
> +                    color={this.state.starIsFilled ? "#C4C4C4" : "#FF4646"}
For now, can you hardcode this in as 
`name={false ? "star" : "star-border"}`
`color={false ? "#C4C4C4" : "#FF4646"}`

later, when you have another variable for star filling, you can replace the boolean constants with the variable

2021-02-13 19:44 UTC, titapa-punpun commented on frontend/components/outcomes/Task.js
> +                    color={this.state.starIsFilled ? "#C4C4C4" : "#3F3F3F"}
Can you rename `starIsFilled` to `checkboxFilled` or `youthCheckboxFilled`?

2021-03-03 00:28 UTC, ryanbeckwith commented
As of 3/2/21, the following changes have been implemented:
-  A valid default state, along with an error message, for any endpoint request that failed to obtain outcomes.
- YDM approval now greys out the star and removes the ability to click on it, and restores the star to unfilled.
- Separate variables (with better names) were added for the filled star and YDM approval attributes.
- Backend GET requests for retrieving Outcome and Task data from Salesforce have been generalized across all pods (and works with high reliability).
- Backend POST requests for the checkbox endpoint have been generalized across all pods (and work with varying reliability)
- Authentication has been enabled for the two relevant backend endpoints (potential varying reliability due to 401 issue).
- User data is derived from the current user logged into the app, not a default user.
- Star and checkbox state is locally preserved during interaction with the Outcome screen, which fixed a bug where the state was reverted to the initial Salesforce value on screen load if the accordion was minimized and reopened.

Furthermore, these are the known issues that still need to be fixed:
- 401 authorization issue occurs for multiple consecutive requests (either GET or POST) to either relevant endpoint if the requests are made within a short period of time.
- 401 authorization issue for updating specific checkbox values in the Associate pod, but not the Trainee pod.
- Undefined error when clicking the star of one specific task (the star in the "Complete Getting Started Module" task of the Life Essentials/Support Network Outcome)

2021-03-03 16:56 UTC, jchin01 requested changes
Just a quick fix of some small things and your PR should be ready!

2021-03-03 16:56 UTC, jchin01 commented on startBackendWindows.sh
> +py ~/OneDrive/Documents/Ryan/School/"College 2nd Year"/JumboCode/MoreThanWords/MoreThanWords/backend/app.py
Please remove your computer specific path and replace it with the original so anyone is able to run the backend windows script

2021-03-03 16:56 UTC, jchin01 commented on frontend/components/pod_components/HomeScreen.js
> +                })}
Looks Good!

2021-03-03 16:56 UTC, jchin01 commented on frontend/components/pod_components/AssociatePod.js
> +                }}
These look good for now to get basic functionality! Nice we can finally start to see outcomes for different pods

2021-03-03 16:56 UTC, jchin01 commented on frontend/components/pod_components/PartnerPod.js
> +                onPress={() => navigation.navigate('Outcomes')}
These lines in the partner pod cause the app to error. I think you need to pass in the information to this pod the same way you did for associates and trainee

2021-03-03 16:56 UTC, jchin01 commented on backend/app.py
> +            response[name]["value"] = value
Nice job cleaning up the response thats sent back to the frontend

2021-03-03 16:56 UTC, jchin01 commented on backend/app.py
> +    app.run(debug=True, host=os.environ['LOCAL_IPV4'])
can you change this back to 0.0.0.0

2021-03-03 16:56 UTC, jchin01 commented on frontend/components/outcomes/Outcome.js
> +export default Outcome;
I like the modularity of breaking the outcome into its own component

2021-03-03 17:22 UTC, jchin01 approved these changes

2021-03-03 17:24 UTC, titapa-punpun approved these changes

2021-03-03 17:24 UTC, titapa-punpun commented on backend/app.py
> +        new_value = False
This can probably be deleted if `new_value` passed in from frontend is a `bool` instead of a `string`

2021-03-03 17:24 UTC, merged