#20: Real User Data and Total Outcomes in Trainee Pod Screen
titapapunne/MoreThanWords pull request #87
Opened 2021-02-20 18:08 UTC by soph-yang

- Added to the outcomes endpoint in app.py to calculate the total number of outcomes and then used that info in the frontend of TraineePod.js for the progress bars
- Change to using real user data instead of fake user data by passing in the user parameter in app.py and by using token in TraineePod.js (also changed from axios to fetch).

**Steps to test PR:** 
- Login in on app using Yichen's account to test having real user data: 
Username: my.waymao@gmail.com
password: ZijReFQ@AJYz3jfrA3iz

- Then after clicking on Trainee Pod from Home Screen, should be able to load all the progress bars with the correct number of total outcomes and completed outcomes.

Can do "print(total_and_completed_outcomes)" in app.py to see all the dictionary with total outcomes info

Standard Checklist:
- [ x ] Does the code work? Does it perform its intended function, the logic is correct etc.
- [ x ] Have you merged the most recent version of staging into your branch?
- [ x ] Are all merge conflicts resolved? 
- [ x ] Can any logging or debugging code be removed? (Any debugging statements should be removed)
- [ x ] Is the `diff` the **minimum amount** needed to achieve this ticket's goal?

2021-02-24 22:54 UTC, jchin01 requested changes
Overall, really good on changing the endpoint to require auth and counting the total number of completed tasks instead of just hardcoding a number! Next steps would be to get rid of all hard coded things in the case that Noah adds a new focus area. We are being a little picky, but it is better to add it now than having to go back to an old project and figure out how to do it. You are really close! Just a few more changes ( i.e take a look at Irinias code) and you'll be there! We are trying to get this done by the end of this sprint and you are quite close!

2021-02-24 22:54 UTC, jchin01 commented on backend/app.py
> +    soql = "SELECT {} FROM Trainee_POD_Map__c".format(','.join(field_names))
Part 1 /2

2021-02-24 22:54 UTC, jchin01 commented on backend/app.py
> +
Part 2/2
So here you are still hard coding for the focus areas. We would want to be able to fetch all focus areas (even if Noah added new focus areas). You should be getting all focus areas from the desc and then SQL selecting for ~all~ focus areas.
Take a look on how Irina did it
` desc = sf.Trainee_POD_Map__c.describe()
     field_names_and_labels = [(field['name'], field['label']) for field in desc['fields']]
     filtered_field_names = [field for field in field_names_and_labels if "Outcomes__c" in field[0]]
     Trainee_field_names = [field[0] for field in filtered_field_names]`

      # salesforce query of each completed outcome # in trainee pod, based on the email and name		     # salesforce query of each completed outcome # in trainee pod, based on the email and name
`     outcomes_result = sf.query(format_soql("SELECT TR_CareerExpl_Outcomes__c, TR_Competency_Outcomes__c, TR_LifeEssentials_Outcomes__c FROM Trainee_POD_Map__c WHERE (Contact__r.email = {email_value} AND Contact__r.name={full_name})",		     soql = "SELECT {} FROM Trainee_POD_Map__c".format(','.join(Trainee_field_names))
                 email_value = email, full_name=name))   		     sf_result = sf.query(format_soql((soql + " WHERE (Contact__r.email = {email_value} AND Contact__r.name={full_name})"), email_value=email, full_name=name))`

2021-02-24 22:54 UTC, jchin01 commented on backend/app.py
> +            car_count += 1
Similar to the comment below, you hard code check for Outcome_COM, Outcome_LIF, etc.. What would happen in the event that Noah added a focus area? Would you be counting the outcomes in the new focus area?

2021-02-24 22:54 UTC, jchin01 commented on frontend/components/pod_components/TraineePod.js
> +                    "Authorization": "Bearer " + accessToken
Good fetch with auth!

2021-02-24 22:54 UTC, jchin01 commented on frontend/components/pod_components/TraineePod.js
> +        life_total_outcomes: 0,
I would try to think of a way to have as many of these as you fetch. For now this works as intended!

2021-02-26 05:47 UTC, soph-yang commented
I got rid of all hardcoded focus areas in the backend when querying the completed num of outcomes and also when calculating the total num of outcomes. I wanted to ask about how to get rid of hardcoding the outcomes fields in the frontend (TraineePod.js), as I don't have that implemented right now

2021-02-26 06:10 UTC, jchin01 reviewed
I will look more into the frontend state setting/ potentially a way we could get around it

2021-02-26 06:10 UTC, jchin01 commented on backend/app.py
> +                sf_result[field_type + "_totalcount"] += 1
This is a really good change to be able to count for any focus areas that could be potentially added.

2021-02-26 06:10 UTC, jchin01 commented on backend/app.py
> +    sf_result = sf.query(format_soql((soql + " WHERE (Contact__r.email = {email_value} AND Contact__r.name={full_name})"), email_value=email, full_name=name))
nicely done

2021-02-27 16:50 UTC, jchin01 approved these changes

2021-02-27 16:50 UTC, merged